### PR TITLE
Update to VS2017, .NET 4.6.2, test new language features

### PR DESCRIPTION
**Pull request by doug24**
and update the NuGet library packages.

Note: I updated the build version to .NET 4.6.2, but the WIX precondition is still at 4.5.2.  I tried to change it to use the  WIX_IS_NETFRAMEWORK_462_OR_LATER_INSTALLED  property.  I have the latest WIX 3.11 installed. The property exists, WIX builds the .msi, and it runs, but it doesn't work: I have .NET 4.7 installed, but it doesn't detect it as higher than 4.6.2, and refuses to install.   I really hate installers <sigh>

Well, let's see if appveyor will build it...

### CODE REVIEW

**Comment by doug24** [comment]
@JVimes maybe you can try updating the conditions.wxi file locally when you have a chance.  

I don't think there's any reason to make a new release with just this changeset.

**Comment by JVimes** [comment]
Sure, we can skip releasing this one. I'm doing the 4.6.2 check at work, successfully. I'll try to take a look before too long and see if I can figure it out. Someday it might be good to switch from Windows Installer to Squirrel (#255).

**Comment by JVimes** [comment]
I changed it to `WIX_IS_NETFRAMEWORK_462_OR_LATER_INSTALLED` in both spots, built and it installs on my machine (up-to-date Windows 10, should have .NET 4.7). Here's my installer local build (old/wrong version number, and had to zip it for GitHub):
[dnGREP 2.9.78 (x64).msi.zip](https://github.com/dnGrep/dnGrep/files/1844927/dnGREP.2.9.78.x64.msi.zip)

Does that one install on your machine?

**Comment by doug24** [comment]
Yes, it did install.  As soon as I read "both spots" in your message, I knew I must have missed the second one.  And yes, it was hidden off the right side of my screen.  doh!

**Comment by JVimes** [comment]
Haha, no worries :) XAML is pretty verbose, so tons of nesting. I'll go ahead and merge this into master.

**Pull request merged**
