### PR TITLE
Everything

### PR DESCRIPTION
**Pull request by doug24**
#291 integration with Everything index service

### CODE REVIEW

**Comment by JVimes** [comment]
Looks like there's a merge conflict keeping the merge button disabled. Weird that the CI build passed.

**Comment by doug24** [comment]
Fixed the conflict.  I started both feature branches off master, so the both passed the CI build at the time they were created, but one the first pull request was merged the second had conflicts.

**Comment by JVimes** [comment]
Oh ya, that makes sense. Thanks!

**Comment by JVimes** [comment]
I'm having a busy couple weeks, but I will try to put a second set of eyes on this before too long.

**Comment by JVimes** [comment]
I'm curious what your general impression is of Everything. I wonder if it has any limits or quirks.
Do you think I should do an installer beta release, now?

**Comment by doug24** [comment]
I would say yes, it would be a good time to do the installer beta release.

I installed Everything on my dev laptop using the Chocolatey package.  It installed both the service and the client, but I had a problem where the index wasn't staying up to date with file additions or deletions. I don't know if I did something wrong or not. I uninstalled it, and reinstalled using the installer from the voidtools.com site.  And it worked fine after that.

Everything does seem pretty easy to use, and the [searching](https://www.voidtools.com/support/everything/searching/) help is useful - there are a lot of options, but you can get by fine with just a few.  It's helpful to spend some time trying searches with the Everything client, or in dnGrep search with an empty search string to just return a file list to get a feel for what works.

Everything is definitely faster than the native search, but the benefits depend on how much time is spent in the rest of the dnGrep operations:  reading files, encoding detection, searching.  I don't know if I'll install it on my work computer or not - the native search is still plenty fast.

A funny thing happened while working on this change: as I was testing I found that the dnGrep UI was freezing during the search, and then finally refreshing when the search was done.  So many files were getting processed that the status bar updates could not keep up, freezing any screen updates.  I had to throttle the updates to keep up with the file processing.

**Comment by JVimes** [comment]
Wow, so the UI (WPF, binding, etc.) couldn't keep up, and it's not that the UI thread was blocked?

I'll do a release build when I get a chance. I've also seen Chocolatey packages behave less desirably than the equivalent installers. It'd be nice if there were an installer tech designed to integrate with Chocolatey.

**Pull request merged**
