### PR TITLE
Add Esc key handler to Preview Window

### PR DESCRIPTION
**Pull request by doug24**
Fix crash from Esc handler in Main Window
Remove WorkspaceViewModel and use normal WPF behaviors to handle the Esc key
Remove orphaned/obsolete classes

### CODE REVIEW

**Comment by doug24** [comment]
There are conflicts with PR #325 - I'll fix when that one is merged

**Comment by JVimes** [comment]
Sounds good, thanks! That one should be merged into Master, now.

**Comment by doug24** [comment]
@JVimes : I haven't built a release before, and tried to follow the notes on the developers page.  I think it worked - it is still a draft replease - but I have a couple questions:  
Do you manually add the source code to the assets?
I have the pushed DraftPrereleaseToGitHub branch that is asking me to create a pull request - did I do something wrong merging to that branch and pushing it to github?  How do I get rid of it?

**Comment by JVimes** [comment]
Neat, thanks for trying it out!

The source code archives are automatically added when you click "Publish Release". I leave the "this is a pre-release" checkbox checked, since we have so little usage it's hard to tell when it's ready.

The pull request banner you mentioned is just a "helpful shortcut". It'll go away on its own. GitHub thinks DraftPrereleaseToGitHub is a normal branch, but really it's just the easiest way I found to tell AppVeyor which commits to publish installers for. A bit of a kludge, but easy and it works.

**Pull request merged**
