### PR TITLE
Baseline update

### PR DESCRIPTION
**Pull request by doug24**
This is a update to .NET 4.5.2, updates to NuGet packages, fixing warnings, updating deprecated code, fixing help links, log file settings, and updating the installer.  No changes to the application functionality yet - I have started fixing some of identified issues, and have a few of them in work.

### CODE REVIEW

**Comment by JVimes** [comment]
Awesome :) I'll take a look as soon as I get a chance.

**Comment by JVimes** [comment]
The CI build is mysteriously broken (AppVeyor is getting 401 from GitHub). I'll try to get that fixed soon.

**Comment by doug24** [comment]
Thank-you!  When you get a new build, I can comment on the issues I think have been addressed.  I have a few more changes queued up in my clone, but I'll hold onto them for now.  Do you want me to increment the version numbers, or do you do that some other way?

**Comment by JVimes** [comment]
Thanks! Smaller merge requests are easier. The Developer Notes section of the wiki has some info on version number scheme. The build config (AppVeyor) holds the version number that actually ends up in product. Version number in source code is overwritten at build don't, oddly, I think, but set it anyway according to the wiki. That'll clue me in as to when to increment numbers in the build config. Someday the build config should follow the version number in source.

**Comment by majkinetor** [comment]
Any chance for new installer to get into the releases  for chocolatey package ?

https://chocolatey.org/packages/dngrep

**Comment by JVimes** [comment]
Thanks for maintaining that! Hopefully soon. GitHub is returning errors when the CI build tries to publish the installers. Fiddled with it some already, but ran out of time. Planning to get to it soonish (maybe this weekend or next). It'll be in pre-release for a little while, as we try it out.

**Comment by JVimes** [comment]
Looks like it's working again 😺 [v2.9.21.0 posted](https://github.com/dnGrep/dnGrep/releases/tag/v2.9.21.0).

**Pull request merged**
