### PR TITLE
Cleanup the UI

### PR DESCRIPTION
**Pull request by kenijo**
Clean up the UI so it better uses the real estate available and gain a few pixels here and there.
Add selection of the current text in the search box so we can right away type in a new value without having to click in the search box.

### CODE REVIEW

**Comment by JVimes** [comment]
@kenijo Looks like this merge breaks the continuous build. You should be able to see the build details like this:

image

**Comment by doug24** [comment]
I got a copy of the code changes and have a few comments.  You have moved the include/exclude file filters off the main panel.  That was one of the issues fixed in the current layout - as requested in Issue #227 and merged over into Issue #1.  It seems odd to undo a change for an issue that was just fixed.

For me, the current layout a great improvement over the previous one, and this seems like a step back. I change the filters a lot - second only to the search text.  I almost never have the expander panel open, and can do everything I need from just the main panel.

I know that others use the tool differently and will have different priories, so I'm open to hearing from others.  Is is really more important to have the encoding selector on the main panel?

For comparison, here is what kenijo's layout looks like:
272-open

272-closed

**Comment by doug24** [comment]
I also have a few code review comments:

1) the "Search Options" label changes when the user presses the Alt key.  The "File Options" text is set in the code behind as part of the trick to make the options panel expand/collapse with an accelerator key.
image
image

2) The "Show search options" selection in the Options dialog breaks the main UI now.  As part of this change, that option and all the property references to it would need to be removed.
image

3) there are some minor layout problems in the search options - clipped text, and alignment of the top and right sides of the file filter:
image

**Comment by JVimes** [comment]
Ah, yes, we had several requests to make the filters immediately accessible in the UI. This is the first request I've seen to move encoding out of the expander. In order to merge this, we need those back in their original locations. If user sentiment swings the other way, we can change it in the future.

Also, just a reminder that this commit seems to have broken the build (see above).

**Comment by kenijo** [comment]
@JVimes: Thanks, it is my first commit ever on GitHub and still need to figure things out. I am not sure I understand why it broke the build but I will look into it. I will separate my two major changes into two different pull requests.

@doug24: I'm pretty new to this code and didn't realize I overrode the changes made for the issue #227. I was really looking at gaining some real estate in the UI. After reading your comments, I realize, a bunch of things I did didn't actually quite make sense. I'll withdraw my pull request and rework my stuff.

**Comment by JVimes** [comment]
@kenijo Oh, welcome to contributing! :) I hope we didn't sound too critical. We really appreciate the help. There's never any harm in submitting a pull request ("PR"). It's a chance for discussion. You can also submit an issue to discuss things before coding them, if it helps.

dnGrep has a server-side build that runs automatically to make sure the build didn't break and the unit tests pass. The PR won't merge into the official repo until the build passes. You can leave a PR open and keep making commits to it (in response to comments, to fix the build, etc.).

Thanks again! Let me know if you have any questions.

**Pull request closed without merging**
