### PR TITLE
Changes for slow performance on large files

### PR DESCRIPTION
**Pull request by doug24**
Added new EolReader to read lines and keep the EOL characters using a char buffer.

Also fixed bug related to Issue #210 where the regex '$' token is used for multiline searches on files with the Windows EOL.  To make the regex work, the Windows EOL has to be changed to a \n only, and this caused the match indexes to be off by one character for each line above it in the file.

### CODE REVIEW

**Comment by doug24** [comment]
@JVimes I guess I need some help here.  The file .\Tests\Files\TestCase15\Issue210unix.txt is supposed to have the unix \n EOL character, and it does on my local repository.  But either on the git commit or pull request, git is changing it to a Windows \r\n, which causes the tests to fail.  I tried changing the git config: git config --global core.autocrlf false, modifying the file and committing it again, but the same thing happened.  Do you know how to fix this?

**Comment by doug24** [comment]
This should work better now: I changed the tests to build the test files on the fly rather than having them stored in the repository.

**Comment by JVimes** [comment]
Ah, thanks Doug! Git sometimes does auto-conversion on checkout and commit. It has repository-specific settings on what to do with newline characters in text files. [Here's the documentation](https://help.github.com/articles/dealing-with-line-endings/#per-repository-settings). I wonder if the pattern matching will let us mark the test-files folder as binary data, so it won't be touched? Generating the data doesn't bother me much, so let me know which route you like best.

**Comment by doug24** [comment]
I think the last change I made to generate the test files is good - don't need to be concerned about settings changing.

**Pull request merged**
