### PR TITLE
323 docking window

### PR DESCRIPTION
**Pull request by doug24**
Docking Preview Window #323
Fix for #241 Highlight in Word Document
Updates to third party libraries

### CODE REVIEW

**Comment by doug24** [comment]
John... if you have time you can see what I did with your library - thanks!  Otherwise, I think it is working well.  

Don't release yet, I have another bug fix in work.

**Comment by JVimes** [comment]
Neat. What changes did you make to DockFloat?

**Comment by doug24** [comment]
I think it really worked quite well, and was pretty easy to use - thanks for the suggestion, and the lib.
I made some style and template changes to the floating window so it's a separate top-level window.
I added code to save and restore the floating window position and state between sessions.
I moved the code to collapse the dock control into a style trigger in the main window because I wanted the docked preview window to be hidden when the preview checkbox is un-checked as well as when the preview is floating.   Couldn't do that with both the control and the main window trying to set the visibility property.

**Comment by JVimes** [comment]
Nice! Glad it worked. When restoring window position, checking to make sure it's not off screen? Maybe the user undocked their laptop, lost extra display. Sorry I don't have time to look at the actual code. Things are super busy at work. Thanks for all the development 🙂

**Comment by doug24** [comment]
Yes, there is code to check if it is off screen.  It worked in the tests I ran  :)

**Comment by JVimes** [comment]
Rock awn. Thank Doug!

**Pull request merged**
